### ISSUE TITLE
[Intégration] planète : background image restante

### ISSUE THREAD

**Issue by FlorentTorregrosa** [Drupal-FR/site-drupalfr#179]
Dans www/themes/custom/drupal_france/scss/modules/_node-planet.scss, il y a :

```scss
  &--wrapper {

    .planet-element--feature-image {
      height:              300px;
      background-image:    url('/themes/custom/drupal_france/images/drupal_planet.png');
      background-position: 50% 50%;
      background-repeat:   no-repeat;
      background-size:     cover;
    }
  }
```

Ce qui fait qu'il y a tout le temps une image de fond sur les articles du planet alors qu'il y a déjà des conditions dans Twig pour avoir cette image par défaut si besoin uniquement.

J'ai remarqué ça en faisant des tests pour #178, avec l'image de base via migrate cela recouvrait le fond donc j'avais pas remarqué avant.
